import { SHADOW_DOCS_KHMER_FONTS, SHADOW_DOCS_LATIN_FONTS } from './ShadowDocsFontCatalog'
import { SHADOW_DOCS_STYLES } from './ShadowDocsStyleCatalog'

const SIZES = [8, 9, 10, 11, 12, 13, 14, 16, 18, 20, 22, 24, 28, 32, 36, 48, 72]
const Button = ({ id, label, active, disabled, onCommand, value = true }) => <button type="button" className={`sd-ribbon-button ${active ? 'is-active' : ''}`} aria-pressed={active || undefined} disabled={disabled} onMouseDown={event => event.preventDefault()} onClick={() => onCommand?.(id, value)}>{label}</button>
const Group = ({ label, children }) => <div className="sd-ribbon-group">{children}<span className="sd-ribbon-group-label">{label}</span></div>

export default function ShadowDocsRibbonHomeTab({ state = {}, onCommand, disabled = false }) {
  return <div className="sd-ribbon-groups" role="tabpanel" aria-label="Home">
    <Group label="Clipboard"><div className="sd-ribbon-row"><Button id="paste" label="Paste" disabled={disabled} onCommand={onCommand}/><Button id="cut" label="Cut" disabled={disabled} onCommand={onCommand}/><Button id="copy" label="Copy" disabled={disabled} onCommand={onCommand}/><Button id="formatPainter" label="Format Painter" disabled={disabled} onCommand={onCommand}/></div></Group>
    <Group label="Font"><div className="sd-ribbon-row"><select className="sd-ribbon-select" aria-label="Font" value={state.fontFamily || 'Noto Serif Khmer'} disabled={disabled} onChange={event => onCommand?.('fontFamily', event.target.value)}><optgroup label="Khmer Fonts">{SHADOW_DOCS_KHMER_FONTS.map(font => <option key={font}>{font}</option>)}</optgroup><optgroup label="Other Fonts">{SHADOW_DOCS_LATIN_FONTS.map(font => <option key={font}>{font}</option>)}</optgroup></select><select className="sd-ribbon-select" aria-label="Font size" value={state.fontSize || 13} disabled={disabled} onChange={event => onCommand?.('fontSize', Number(event.target.value))}>{SIZES.map(size => <option key={size}>{size}</option>)}</select><Button id="growFont" label="A+" disabled={disabled} onCommand={onCommand}/><Button id="shrinkFont" label="A−" disabled={disabled} onCommand={onCommand}/></div><div className="sd-ribbon-row"><Button id="bold" label="B" active={state.bold} disabled={disabled} onCommand={onCommand} value={!state.bold}/><Button id="italic" label="I" active={state.italic} disabled={disabled} onCommand={onCommand} value={!state.italic}/><Button id="underline" label="U" active={state.underline} disabled={disabled} onCommand={onCommand} value={!state.underline}/><Button id="strike" label="abc̶" active={state.strike} disabled={disabled} onCommand={onCommand} value={!state.strike}/><Button id="subscript" label="x₂" active={state.subscript} disabled={disabled} onCommand={onCommand} value={!state.subscript}/><Button id="superscript" label="x²" active={state.superscript} disabled={disabled} onCommand={onCommand} value={!state.superscript}/><Button id="clearFormatting" label="Clear" disabled={disabled} onCommand={onCommand}/><label className="sd-ribbon-color">Highlight<input type="color" value={state.backgroundColor || '#fff176'} disabled={disabled} onChange={event => onCommand?.('highlight', event.target.value)}/></label><label className="sd-ribbon-color">Color<input type="color" value={state.color || '#242139'} disabled={disabled} onChange={event => onCommand?.('color', event.target.value)}/></label></div></Group>
    <Group label="Paragraph"><div className="sd-ribbon-row">{[['bullets','• List'],['numbering','1. List'],['multilevelList','1.1 List'],['decreaseIndent','← Indent'],['increaseIndent','Indent →'],['sort','A→Z'],['showMarks','¶'],['alignLeft','Left'],['alignCenter','Center'],['alignRight','Right'],['justify','Justify'],['lineSpacing','Spacing'],['shading','Shading'],['borders','Borders']].map(([id,label]) => <Button key={id} id={id} label={label} active={id.startsWith('align') && state.alignment === id.replace('align','').toLowerCase() || id === 'justify' && state.alignment === 'justify'} disabled={disabled} onCommand={onCommand}/>)}</div></Group>
    <Group label="Styles"><div className="sd-ribbon-style-gallery">{SHADOW_DOCS_STYLES.map(style => <button key={style.id} type="button" className={`sd-ribbon-style ${state.styleId === style.id ? 'is-active' : ''}`} disabled={disabled} onClick={() => onCommand?.('style', style.id)}>{style.label}</button>)}</div></Group>
    <Group label="Editing"><div className="sd-ribbon-row"><Button id="find" label="Find" disabled={disabled} onCommand={onCommand}/><Button id="replace" label="Replace" disabled={disabled} onCommand={onCommand}/><Button id="select" label="Select" disabled={disabled} onCommand={onCommand}/></div></Group>
  </div>
}
