const Button = ({ id, label, active, disabled, onCommand, value = true }) => <button type="button" className={`sd-ribbon-button ${active ? 'is-active' : ''}`} disabled={disabled} onClick={() => onCommand?.(id, value)}>{label}</button>

export default function ShadowDocsRibbonLayoutTab({ state = {}, onCommand, disabled = false }) {
  return <div className="sd-ribbon-groups" role="tabpanel" aria-label="Layout">
    <div className="sd-ribbon-group"><div className="sd-ribbon-row"><Button id="margins" label="Margins" disabled={disabled} onCommand={onCommand}/><Button id="orientation" label={state.orientation === 'landscape' ? 'Landscape' : 'Portrait'} disabled={disabled} onCommand={onCommand}/><Button id="paperSize" label={state.pageSize || 'A5'} disabled={disabled} onCommand={onCommand}/><Button id="columns" label={`Columns ${state.columns || 1}`} disabled={disabled} onCommand={onCommand}/><Button id="breaks" label="Breaks" disabled={disabled} onCommand={onCommand}/><Button id="lineNumbers" label="Line Numbers" active={state.lineNumbers} disabled={disabled} onCommand={onCommand} value={!state.lineNumbers}/><Button id="hyphenation" label="Hyphenation" active={state.hyphenation} disabled={disabled} onCommand={onCommand} value={!state.hyphenation}/><Button id="textDirection" label="Text Direction" disabled={disabled} onCommand={onCommand}/></div><span className="sd-ribbon-group-label">Page Setup</span></div>
    <div className="sd-ribbon-group"><div className="sd-ribbon-row">{[['indentLeft','Left',state.indentLeft],['indentRight','Right',state.indentRight],['spaceBefore','Before',state.spaceBefore],['spaceAfter','After',state.spaceAfter]].map(([id,label,value]) => <label key={id} className="sd-ribbon-number">{label}<input type="number" value={value ?? 0} disabled={disabled} onChange={event => onCommand?.(id, Number(event.target.value))}/></label>)}</div><span className="sd-ribbon-group-label">Paragraph</span></div>
    <div className="sd-ribbon-group"><div className="sd-ribbon-row">{[['position','Position'],['wrapText','Wrap Text'],['bringForward','Bring Forward'],['sendBackward','Send Backward'],['selectionPane','Selection Pane'],['alignObjects','Align'],['groupObjects','Group'],['rotate','Rotate']].map(([id,label]) => <Button key={id} id={id} label={label} disabled={disabled} onCommand={onCommand}/>)}</div><span className="sd-ribbon-group-label">Arrange</span></div>
  </div>
}
