export const youMightLikeBooks = [
  {
    id: 601,
    title: 'Name Book',
    cover: '/assets/YouMightLike/YouMightLike 1.jpg',
    likes: '1000',
    episodes: 'Ep 17',
    link: '/story/601',
  },
  {
    id: 602,
    title: 'Name Book',
    cover: '/assets/YouMightLike/YouMightLike 2.jpg',
    likes: '920',
    episodes: 'Ep 21',
    link: '/story/602',
  },
  {
    id: 603,
    title: 'Name Book',
    cover: '/assets/YouMightLike/YouMightLike 3.jpg',
    likes: '860',
    episodes: 'Ep 14',
    link: '/story/603',
  },
  {
    id: 604,
    title: 'Name Book',
    cover: '/assets/YouMightLike/YouMightLike 4.jpg',
    likes: '1.4k',
    episodes: 'Ep 31',
    link: '/story/604',
  },
  {
    id: 605,
    title: 'Name Book',
    cover: '/assets/YouMightLike/YouMightLike 5.jpg',
    likes: '980',
    episodes: 'Ep 19',
    link: '/story/605',
  },
  {
    id: 606,
    title: 'Name Book',
    cover: '/assets/YouMightLike/YouMightLike 6.jpg',
    likes: '710',
    episodes: 'Ep 12',
    link: '/story/606',
  },
]
